export const ROLE_ADMIN = "ADMIN";
export const ROLE_WALKER = "CUVAR";
export const ROLE_OWNER = "VLASNIK";
export const STATUS_ACTIVE = "ACTIVE";
export const STATUS_BLOCKED = "BLOCKED";
export const STATUS_REQUESTED = "REQUESTED";
export const CATEGORY_NUDIM = "Nudim čuvanje";
export const CATEGORY_TRAZIM = "Tražim čuvanje";
export const CATEGORY_OSTALO = "Ostalo";